<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Análise Correlação RRAS 2024</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="analise_correlacao_rras_files/libs/clipboard/clipboard.min.js"></script>
<script src="analise_correlacao_rras_files/libs/quarto-html/quarto.js"></script>
<script src="analise_correlacao_rras_files/libs/quarto-html/popper.min.js"></script>
<script src="analise_correlacao_rras_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analise_correlacao_rras_files/libs/quarto-html/anchor.min.js"></script>
<link href="analise_correlacao_rras_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analise_correlacao_rras_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analise_correlacao_rras_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analise_correlacao_rras_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analise_correlacao_rras_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="analise_correlacao_rras_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="analise_correlacao_rras_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Conteúdo</h2>
   
  <ul>
  <li><a href="#métodos" id="toc-métodos" class="nav-link active" data-scroll-target="#métodos">Métodos</a>
  <ul class="collapse">
  <li><a href="#correlação-de-spearman" id="toc-correlação-de-spearman" class="nav-link" data-scroll-target="#correlação-de-spearman">Correlação de Spearman</a></li>
  <li><a href="#variáveis-utilizadas" id="toc-variáveis-utilizadas" class="nav-link" data-scroll-target="#variáveis-utilizadas">Variáveis utilizadas</a></li>
  </ul></li>
  <li><a href="#análise-de-correlação" id="toc-análise-de-correlação" class="nav-link" data-scroll-target="#análise-de-correlação">Análise de correlação</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise Correlação RRAS 2024</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="métodos" class="level1">
<h1>Métodos</h1>
<p>Para a realização deste estudo, foram utilizados dados provenientes das bases oficiais do Sistema de Informação sobre Nascidos Vivos (SINASC), com foco nos dados de parturientes residentes no Estado de São Paulo, no ano de 2024. Realizando associações com dados fornecidos pelo Departamento de Gestão Interfederativa e Participativa (DGIP) da Secretaria Executiva (SE) do Ministério da Saúde (MS), e disponibilizados pelo Departamento de Monitoramento, Avaliação e Disseminação de Informações Estratégicas em Saúde (DEMAS) da Secretaria de Informação e Saúde Digital (SEIDIGI) <span class="citation" data-cites="infoms">(<a href="#ref-infoms" role="doc-biblioref">Ministério da Saúde 2025</a>)</span>, também foi possível separar os registros em suas respectivas Redes Regionais de Atenção à Saúde (RRAS). A partir disso, realizou-se uma limpeza nos dados para identificar os casos em que a idade gestacional era maior ou igual a 22 semanas ou, nos casos em que não havia informação sobre a idade gestacional, identificar os casos em que o peso do recém-nascido era maior que 500 gramas. Dessa maneira, obteve-se os dados gerais dos nascidos vivos do Estado de São Paulo nos anos de 2012.</p>
<p>Para identificar os partos prematuros, aplicou-se um filtro de idade gestacional aos dados de nascidos vivos. Foram classificados como parto prematuro (PP) todos os nascimentos com idade gestacional entre 22 e 36 semanas. Na etapa seguinte, para distinguir entre partos prematuros espontâneos (PPes) e eletivos (PPel), foram utilizadas as variáveis STTRABPART, que indica a ocorrência de trabalho de parto induzido, e STCESPARTO, que informa se foi realizada cesárea antes do início do trabalho de parto.</p>
<p>Assim, caso não houvesse trabalho de parto induzido e não houvesse cesárea antes do início do trabalho de parto, os dados eram classificados como partos prematuros espontâneos. Os demais casos em que havia alguma informação sobre o trabalho de parto foram classificados como partos prematuros eletivos. A tabela a seguir apresenta detalhadamente a classificação dos tipos de parto.</p>
<div class="cell" data-warnings="false" data-tab-label="{}">
<table class="table table-sm table-striped small">
<caption>Classificação do tipo de parto</caption>
<colgroup>
<col style="width: 36%">
<col style="width: 40%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Trabalho de parto induzido</th>
<th style="text-align: center;">Cersárea antes do trabalho de parto</th>
<th style="text-align: center;">Resultado do parto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Espontâneo</td>
</tr>
<tr class="even">
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Eletivo</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Eletivo</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Eletivo</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sem informação</td>
<td style="text-align: center;">Sem informação</td>
<td style="text-align: center;">Não tem como avaliar</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sem informação</td>
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Não tem como avaliar</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sem informação</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Eletivo</td>
</tr>
<tr class="even">
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Sem informação</td>
<td style="text-align: center;">Não tem como avaliar</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Sem informação</td>
<td style="text-align: center;">Eletivo</td>
</tr>
</tbody>
</table>
</div>
<p>As porcentagens utilizadas ao longo do relatório foram calculadas diretamente a partir dos valores absolutos obtidos nas filtragens anteriores. A porcentagem de partos prematuros em relação ao total de nascidos vivos foi obtida dividindo-se o número total de partos prematuros pelo total de nascidos vivos e multiplicando o resultado por 100. De maneira semelhante, esse processo foi aplicado para calcular as porcentagens de partos prematuros eletivos e partos prematuros espontâneos em relação ao total de nascidos vivos e ao total de partos prematuros, criando diferentes taxas para a análise. Empregando esse procedimento para todos esses casos, foi possível adicionar ao banco de dados informações relativas aos anos no Estado de São Paulo como um todo e também informações relativas aos anos e às RRAS separadamente.</p>
<p>A análise das associações entre as variáveis foi realizada por meio do coeficiente de correlação de Spearman. A escolha desse método se justifica por se tratar de uma medida não paramétrica, adequada para avaliar relações monotônicas entre variáveis, sem a necessidade de assumir normalidade na distribuição dos dados.</p>
<p>Foram calculadas as correlações entre os indicadores de prematuridade e variáveis sociodemográficas, de cobertura assistencial e de condições de saúde. Adicionalmente, foram obtidos os valores de p para cada correlação, permitindo a avaliação da significância estatística das associações observadas.</p>
<p>Para fins interpretativos, consideraram-se estatisticamente significativas as correlações com p-valor inferior a 0,05.</p>
<section id="correlação-de-spearman" class="level2">
<h2 class="anchored" data-anchor-id="correlação-de-spearman">Correlação de Spearman</h2>
<p>O coeficiente de correlação de Spearman (rho ou <span class="math inline">\(\rho\)</span>) avalia a força e a direção da associação entre duas variáveis através de uma relação monotônica. Trata-se de um método não paramétrico, pois ele não exige a suposição de que os dados sigam uma distribuição normal, sendo baseado nos postos dos valores ao invés dos valores brutos <span class="citation" data-cites="Spearman_1904">(<a href="#ref-Spearman_1904" role="doc-biblioref">Spearman 1904</a>)</span>.</p>
<p>O teste avalia as seguintes hipóteses estatísticas:</p>
<ul>
<li><p>Hipótese nula (<span class="math inline">\(H_0\)</span>): Não há associação monotônica entre as duas variáveis (as variáveis são independentes).</p></li>
<li><p>Hipótese alternativa (<span class="math inline">\(H_1\)</span>): Existe uma associação monotônica entre as variáveis (os postos de uma variável tendem a aumentar ou diminuir em relação aos postos da outra).</p></li>
</ul>
<p>Dentre os resultados fornecidos por esta análise, destacam-se as seguintes medidas:</p>
<ul>
<li><p>O Coeficiente: Esta medida de associação varia entre -1 e 1. Um valor de 1 indica uma correlação monotônica positiva perfeita, -1 indica uma correlação monotônica negativa perfeita, e 0 indica a ausência de associação monotônica.</p></li>
<li><p>Significância (p-valor): Representa a probabilidade de observar uma correlação tão forte quanto a calculada caso a hipótese nula fosse verdadeira. Assim como em outros testes de associação, considera-se o resultado estatisticamente significativo quando o p-valor é menor que 0.05.</p></li>
</ul>
<p>Para a realização das análises no ambiente R, utiliza-se a função nativa <code>cor.test()</code>, especificando o argumento <code>method = "spearman"</code>. Esta função calcula tanto o coeficiente de correlação quanto a significância estatística necessária para a interpretação dos dados.</p>
<p>Os resultados são apresentados no relatório destacando o coeficiente de correlação, que indica a magnitude da associação, e o p-valor correspondente, onde p &lt; 0.05 é considerado significativo e p &lt; 0.01 é considerado altamente significativo para rejeitar a independência entre as variáveis.</p>
</section>
<section id="variáveis-utilizadas" class="level2">
<h2 class="anchored" data-anchor-id="variáveis-utilizadas">Variáveis utilizadas</h2>
<p>Foram incluídas na análise variáveis relacionadas à prematuridade, características socioeconômicas e indicadores de assistência à saúde. Entre os indicadores de prematuridade, consideraram-se a taxa de partos prematuros (tx_PP), a taxa de partos prematuros eletivos (tx_PPel) e a taxa de partos prematuros espontâneos (tx_PPes). No que se refere aos indicadores de saúde materna e fetal, foram analisadas a razão de mortalidade materna (rz_mort_mat), a taxa de mortalidade fetal (tx_mort_fetal) e a porcentagem de óbitos fetais potencialmente evitáveis (porc_obitos_fetais_evitaveis). Como indicador socioeconômico, utilizou-se o Índice de Desenvolvimento Humano (IDH_2022). Além disso, foram incluídos indicadores de acesso e qualidade da atenção à saúde, como a cobertura populacional da atenção básica (cob_pop_AB), a cobertura da Estratégia Saúde da Família (cob_pop_SF), a porcentagem de mulheres com mais de sete consultas de pré-natal (porc_mais_7_pre_natal), o início precoce do pré-natal (porc_pre_natal_precoec), a adequação do pré-natal (porc_pre_natal_adequado) e a porcentagem de usuárias exclusivas do Sistema Único de Saúde (porc_exclusivas_SUS). Todas essas variáveis foram analisadas no nível das Redes Regionais de Atenção à Saúde (RRAS) para o ano de 2024.</p>
</section>
</section>
<section id="análise-de-correlação" class="level1">
<h1>Análise de correlação</h1>
<p>Apresentam-se a seguir os gráficos e tabelas de correlação, assim como os gráficos de dispersão e suas respectivas interpretações, com ênfase nos indicadores relacionados à prematuridade.</p>
<div id="fig-corrplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/corrplot.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Matriz de correlação entre variáveis</figcaption>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<caption>Tabela 1: Valores p e coeficientes de Spearman significativos entre os indicadores de prematuridade e os indicadores sociodemográficos, de cobertura assistencial e de condições de saúde no ano de 2024. </caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Indicadores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Coeficiente</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Valor p</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Conclusão do teste</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">porc_mais_7_pre_natal x porc_pre_natal_adequado</td>
<td style="text-align: left;">0.9293</td>
<td style="text-align: center;">0.0000</td>
<td style="text-align: center;">Altamente significativa</td>
</tr>
<tr class="even">
<td style="text-align: left;">cob_pop_AB x cob_pop_SF</td>
<td style="text-align: left;">0.7888</td>
<td style="text-align: center;">0.0001</td>
<td style="text-align: center;">Altamente significativa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tx_PP x tx_PPel</td>
<td style="text-align: left;">0.7276</td>
<td style="text-align: center;">0.0006</td>
<td style="text-align: center;">Altamente significativa</td>
</tr>
<tr class="even">
<td style="text-align: left;">IDH_2022 x porc_exclusivas_SUS</td>
<td style="text-align: left;">-0.7176</td>
<td style="text-align: center;">0.0008</td>
<td style="text-align: center;">Altamente significativa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cob_pop_AB x porc_exclusivas_SUS</td>
<td style="text-align: left;">0.6105</td>
<td style="text-align: center;">0.0071</td>
<td style="text-align: center;">Altamente significativa</td>
</tr>
<tr class="even">
<td style="text-align: left;">cob_pop_SF x tx_PPes</td>
<td style="text-align: left;">0.6016</td>
<td style="text-align: center;">0.0083</td>
<td style="text-align: center;">Altamente significativa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">porc_mais_7_pre_natal x tx_PPes</td>
<td style="text-align: left;">0.5995</td>
<td style="text-align: center;">0.0086</td>
<td style="text-align: center;">Altamente significativa</td>
</tr>
<tr class="even">
<td style="text-align: left;">porc_pre_natal_precoce x rz_mort_mat</td>
<td style="text-align: left;">-0.5480</td>
<td style="text-align: center;">0.0186</td>
<td style="text-align: center;">Significativa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">porc_mais_7_pre_natal x tx_mort_fetal</td>
<td style="text-align: left;">-0.5067</td>
<td style="text-align: center;">0.0319</td>
<td style="text-align: center;">Significativa</td>
</tr>
<tr class="even">
<td style="text-align: left;">cob_pop_AB x tx_PPes</td>
<td style="text-align: left;">0.4788</td>
<td style="text-align: center;">0.0444</td>
<td style="text-align: center;">Significativa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">porc_pre_natal_adequado x tx_PPes</td>
<td style="text-align: left;">0.4788</td>
<td style="text-align: center;">0.0444</td>
<td style="text-align: center;">Significativa</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Observa-se inicialmente na Figura 1 e na Tabela 1 uma forte correlação positiva entre a taxa de partos prematuros totais e a taxa de partos prematuros eletivos (<span class="math inline">\(\rho\)</span> = 0,73), indicando que a variação da prematuridade total é fortemente influenciada pelos partos prematuros de natureza eletiva. Em contrapartida, a correlação entre prematuridade total e prematuridade espontânea foi mais fraca (<span class="math inline">\(\rho\)</span> = 0,31), sugerindo menor contribuição relativa desse componente.</p>
<p>A taxa de partos prematuros espontâneos apresentou correlações positivas moderadas a fortes com indicadores de cobertura e acesso à atenção primária, como a cobertura da Estratégia Saúde da Família (<span class="math inline">\(\rho\)</span> = 0,60), cobertura da atenção básica (<span class="math inline">\(\rho\)</span> = 0,48) e proporção de mulheres com mais de sete consultas de pré-natal (<span class="math inline">\(\rho\)</span> = 0,60). Por outro lado, a taxa de prematuridade espontânea apresentou correlação negativa com a taxa de mortalidade fetal (<span class="math inline">\(\rho\)</span> = -0,35).</p>
<p>Os resultados do teste de Spearman indicam que a taxa de partos prematuros totais apresentou correlação estatisticamente significativa apenas com a taxa de partos prematuros eletivos (p &lt; 0,001), evidenciando que a variação da prematuridade total é fortemente influenciada por esse componente.</p>
<p>De forma semelhante, a taxa de partos prematuros eletivos apresentou correlação significativa apenas com a prematuridade total, não sendo observadas associações estatisticamente significativas com os demais indicadores analisados.</p>
<p>Por outro lado, a taxa de partos prematuros espontâneos apresentou correlações estatisticamente significativas com indicadores de acesso e qualidade da atenção à saúde, incluindo a cobertura da atenção básica (p = 0,044), a cobertura da Estratégia Saúde da Família (p = 0,008), a proporção de mulheres com mais de sete consultas de pré-natal (p = 0,009) e a adequação do pré-natal (p = 0,044).</p>
<p>Além disso, avaliando as demais variáveis, verificou-se uma associação positiva altamente significativa (<span class="math inline">\(\rho\)</span> = 0.9293; p = 0.0000) entre a proporção de mulheres com mais de 7 consultas de pré-natal e a proporção de pré-natal adequado, indicando que maiores percentuais de realização de consultas estão relacionados a maior adequação do acompanhamento pré-natal. De forma consistente, a cobertura populacional de atenção básica apresenta associação positiva altamente significativa com a cobertura por equipes de Saúde da Família (<span class="math inline">\(\rho\)</span> = 0.7888; p = 0.0001), evidenciando que maiores níveis de uma cobertura estão relacionados a maiores níveis da outra.</p>
<p>Por outro lado, observou-se que o IDH de 2022 apresenta associação negativa altamente significativa com a proporção de usuárias exclusivas do SUS (<span class="math inline">\(\rho\)</span> = −0.7176; p = 0.0008), indicando que valores mais elevados de IDH estão relacionados a menores proporções dessa população. Em contrapartida, a cobertura de atenção básica mostra associação positiva altamente significativa com a proporção de usuárias exclusivas do SUS (<span class="math inline">\(\rho\)</span> = 0.6105; p = 0.0071), sugerindo que maiores níveis de cobertura estão associados a maiores proporções de usuárias exclusivas do SUS.</p>
<p>Por fim, pode-se observar que a proporção de início precoce do pré-natal apresenta associação negativa significativa com a razão de mortalidade materna (<span class="math inline">\(\rho\)</span> = −0.5480; p = 0.0186), assim como a proporção de mulheres com mais de 7 consultas de pré-natal também apresenta associação negativa significativa com a taxa de mortalidade fetal (<span class="math inline">\(\rho\)</span> = −0.5067; p = 0.0319), indicando que o pré-natal iniciado precocemente está relacionado a menores razões de morte materna e que mais de 7 consultas de pré-natal estão relacionadas a menores taxas de mortalidade fetal.</p>
<p>A seguir, tem-se os gráficos de dispersão das relações entre as variáveis com correlações significativas de acordo com a correlação de Spearman, com o intuito de complementar as análises realizadas através da correlação de Spearman.</p>
<div id="fig-corr1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_1.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Dispersão entre porc_mais_7_pre_natal e porc_pre_natal_adequado</figcaption>
</figure>
</div>
<p>O gráfico de dispersão entre a porcentagem de mulheres com mais de 7 consultas de pré-natal e a porcentagem de pré-natal adequado revela uma associação positiva altamente significativa, perceptível pela reta de tendência geral acentuada, indicando que maiores percentuais de consultas estão diretamente relacionados a uma maior adequação do acompanhamento nas redes regionais. As RRAS 11, 12 e 18 apresentam os maiores índices em ambos os indicadores, situando-se no extremo superior direito da distribuição, enquanto as RRAS 2 e 5 ocupam o extremo oposto com os menores valores registrados. Nota-se que a RRAS 15 apresenta um desvio em relação à tendência geral.</p>
<div id="fig-corr2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_2.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Dispersão entre cob_pop_AB e cob_pop_SF</figcaption>
</figure>
</div>
<p>A análise da cobertura populacional de atenção básica em relação à cobertura por equipes de Saúde da Família demonstra uma associação positiva altamente significativa. As RRAS 11, 10 e 12 destacam-se pelas maiores porcentagens de cobertura em ambas as modalidades. Em contrapartida, as RRAS 4, 5 e 16 apresentam coberturas de Saúde da Família que se posicionam bem abaixo da linha de tendência central.</p>
<div id="fig-corr3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_3.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Dispersão entre tx_PP e tx_PPel</figcaption>
</figure>
</div>
<p>Na relação entre a taxa de partos prematuros e a taxa de partos prematuros eletivos, as RRAS 18 e 5 registram as taxas mais elevadas para ambos os indicadores, ao passo que as RRAS 8, 4 e 6 concentram-se nos menores valores tanto de prematuridade total quanto de prematuridade eletiva.</p>
<div id="fig-corr4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_4.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Dispersão entre IDH_2022 e porc_exclusivas_SUS</figcaption>
</figure>
</div>
<p>Na Figura 4, observa-se que as RRAS 6 e 1 ocupam o quadrante inferior direito do gráfico, caracterizado pelo maior IDH e menor dependência exclusiva do SUS, enquanto as RRAS 10, 8 e 11 situam-se no extremo oposto, apresentando menores índices de IDH acompanhados das maiores proporções de usuárias exclusivas.</p>
<div id="fig-corr5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_5.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Dispersão entre cob_pop_AB e porc_exclusivas_SUS</figcaption>
</figure>
</div>
<p>Na Figura 5, percebe-se que as RRAS 10, 11 e 12 encontram-se no quadrante superior direito, apresentando altos índices em ambos os indicadores simultaneamente. Em contrapartida, a RRAS 1 configura-se como um desvio à tendência geral da amostra, mantendo uma cobertura de atenção básica superior a 70%, porém registrando a menor proporção de usuárias exclusivas do SUS entre todas as redes regionais.</p>
<div id="fig-corr6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_6.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Dispersão entre cob_pop_SF e tx_PPes</figcaption>
</figure>
</div>
<p>Na dispersão entre a cobertura populacional da Estratégia Saúde da Família e a taxa de partos prematuros espontâneos, a RRAS 11 posicionou-se no extremo superior de cobertura e taxa, enquanto as RRAS 2, 4 e 5 apresentam os menores valores para ambos os indicadores. A RRAS 15 destaca-se como um ponto atípico, apresentando a maior taxa de prematuridade espontânea do conjunto de dados, apesar de possuir uma cobertura de Saúde da Família em patamar intermediário.</p>
<div id="fig-corr7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_7.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;8: Dispersão entre porc_mais_7_pre_natal e tx_PPes</figcaption>
</figure>
</div>
<p>Pelo gráfico, percebe-se que as RRAS 11 e 12 posicionam-se com altos valores em ambos os indicadores, enquanto a RRAS 2 apresenta os menores índices tanto de consultas quanto de prematuridade espontânea. A RRAS 15 aparece novamente como um ponto atípico na distribuição, apresentando a maior taxa de prematuridade espontânea entre todas as regiões, apesar de possuir um percentual de consultas superior a 85%.</p>
<div id="fig-corr8" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_8.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;9: Dispersão entre porc_pre_natal_precoce e rz_mort_mat</figcaption>
</figure>
</div>
<p>O gráfico de dispersão da relação entre porcentagens de pré-natal precoce e razão de mortalidade materna mostra que as RRAS 18, 15 e 7 concentram-se no quadrante superior esquerdo, com menores percentuais de início precoce e razões de mortalidade mais elevadas. Por outro lado, a RRAS 10 apresenta o maior percentual de início precoce do pré-natal e a menor razão de mortalidade materna do conjunto de dados, posicionando-se no extremo inferior direito da tendência observada.</p>
<div id="fig-corr9" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_9.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;10: Dispersão entre porc_mais_7_pre_natal e tx_mort_fetal</figcaption>
</figure>
</div>
<p>No gráfico de dispersão, a RRAS 2 destaca-se no extremo superior esquerdo, registrando a maior taxa de mortalidade fetal acompanhada pelo menor percentual de realização de mais de 7 consultas. No extremo oposto, as RRAS 10, 12, 16 e 15 situam-se no quadrante inferior direito, apresentando alta cobertura de consultas e as menores taxas de mortalidade fetal observadas no período.</p>
<div id="fig-corr10" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_10.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;11: Dispersão entre cob_pop_AB e tx_PPes</figcaption>
</figure>
</div>
<p>No gráfico da Figura 10, é visto que as RRAS 11 e 12 posicionam-se no extremo superior direito da tendência, enquanto as RRAS 2 e 5 ocupam o extremo inferior esquerdo. A RRAS 15 destaca-se como um ponto isolado no topo da distribuição, apresentando a maior taxa de prematuridade espontânea do estado para um nível intermediário de cobertura assistencial, ao passo que as RRAS 4 e 16 registram taxas de prematuridade espontânea reduzidas apesar de possuírem coberturas de atenção básica superiores a 70%.</p>
<div id="fig-corr11" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="f3_graficos/grafico_11.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;12: Dispersão entre porc_pre_natal_adequado e tx_PPes</figcaption>
</figure>
</div>
<p>Pelo gráfico de dispersão da relação entre a porcentagem de pré-natais adequados e a taxa de prematuridade espontânea, as RRAS 11 e 12 situam-se no quadrante superior direito, combinando altos índices de adequação de pré-natal e taxas elevadas de prematuridade espontânea, enquanto a RRAS 2 posiciona-se no extremo oposto com os menores valores para ambas as variáveis. A RRAS 15 configura-se novamente como o principal desvio da tendência central, mantendo a taxa mais elevada de prematuridade espontânea da amostra, enquanto a RRAS 16 apresenta uma das menores taxas observadas.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-infoms" class="csl-entry" role="listitem">
Ministério da Saúde. 2025. <span>“<span class="nocase">Macrorregiões e Regiões de Saúde</span>.”</span> <a href="https://infoms.saude.gov.br/extensions/SEIDIGI_DEMAS_MACRORREGIOES/SEIDIGI_DEMAS_MACRORREGIOES.html">https://infoms.saude.gov.br/extensions/SEIDIGI_DEMAS_MACRORREGIOES/SEIDIGI_DEMAS_MACRORREGIOES.html</a>.
</div>
<div id="ref-Spearman_1904" class="csl-entry" role="listitem">
Spearman, Charles. 1904. <span>“The Proof and Measurement of Association Between Two Things.”</span> <em>The American Journal of Psychology</em> 15 (1): 72–101. <a href="https://doi.org/10.2307/1412159">https://doi.org/10.2307/1412159</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>